### ISSUE TITLE
which branch to use? UTF issue still alive

### ISSUE THREAD

**Issue by whitas** [pe-st/garmin-connect-export#8] opened 2018-06-28 09:00 UTC
Hi all

Which branch to use ;) ? Is develop most up to date? Will all changes merged to master someday?

In both develop and master I have still UTF issue

```
Garmin Connect activity: [2806957153] Maszyna eliptyczna
	Wt, 26 cze 2018 17:38, 	Downloading file... Traceback (most recent call last):
  File "/Users/tomek/Garmin/garmin-connect-export//gcexport3.py", line 371, in <module>
    write_to_file(data_filename, data.decode(), file_mode)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 12: invalid continuation byte

```

**Comment by pe-st** [comment] 2018-07-03 12:43
Hello @whitas 

The Python 3 script (`gcexport3.py`) is the same in the `develop` and `master` branches; for the time being I just keep them for comparison purposes.

My own development happens in the Python 2 script (`gcexport.py`) on the `develop` branch. There are some things I want to implement yet before consolidating the two scripts.

Is the UTF-8 issue also present with `gcexport.py`?

**Comment by pe-st** [comment] 2018-07-06 06:32
Hello @whitas 

I've added some notes about branches and forks in the README to make clear that in this repo here only the Python 2 version of the script is maintained (and I removed `gcexport3.py` in my repo).
So the question about the branch is answered and I'm closing the issue.

For the UTF issue: this is still a duplicate of https://github.com/moderation/garmin-connect-export/issues/14

**Closed by pe-st** 2018-07-06 06:32 UTC

**Comment by whitas** [comment] 2018-07-06 07:42
Hi. I don't know if UTF-8 issue also present with gcexport.py because there is HTTP404 issue and script fails to download anything.

**Comment by whitas** [comment] 2018-07-06 07:47
Oh.. sorry this 404 issue is from the second repo "moderation" as well as UTF8. It's just a bit confusing me with git that I'm not fully aware which repo and which branch from repo I'm using.

Anyway - gcexport.py from here is working ok now for me.
